### ISSUE TITLE
Cannot open links

### ISSUE THREAD

**Issue by geovnn** [felipebueno/stacker_news#24]
Cannot open any link.
May be related to #23 #20

![screenshot](https://github.com/user-attachments/assets/aaefcf53-7653-436e-930f-eea19bc6ae0e)

**Comment by felipebueno** [comment]
Hey @geovnn you just won the badge of the first real issue not created by me :grin:

Nice to know there's someone else using my app out there :) 

I'll take a look at it tomorrow and I'll let you know when it's fixed. Thanks!
